name: react-native-android-build-apk
on: [push]
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
        run: |
          yarn && yarn lint && yarn test
          cd react-native-in-app-payments-quickstart && yarn && yarn lint && cd ..
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd react-native-in-app-payments-quickstart && npm install
          cd android && chmod +x ./gradlew
          ./gradlew assembleRelease