name: react-native-android-build-apk
on: [push]
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: |
          yarn && yarn lint && yarn test
          cd react-native-in-app-payments-quickstart && yarn && yarn lint && cd .. 

  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:      
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-                
      - name: Install npm dependencies  
        uses: actions/checkout@v2
      - run: |
          cd react-native-in-app-payments-quickstart && yarn
          cd android && ./gradlew clean build        

  build-ios:
    needs: install-and-test
    runs-on: macos-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: |
          gem install cocoapods
          cd react-native-in-app-payments-quickstart
          yarn
          cd ios
      - run: pod install
        working-directory: ios
        name: Install pod dependencies
      - name: Build iOS (debug)
        run: |
          xcodebuild -workspace RNInAppPaymentsQuickstart.xcworkspace -configuration Debug
          -scheme RNInAppPaymentsQuickstart -destination "platform=iOS Simulator,OS=12.2,name=iPhone
          X" -derivedDataPath build/RNInAppPaymentsQuickstart   